---
algolia:
  application_id: ~
  index_name: ~
  powered_by: ~
  search_only_api_key: ~
analytics:
  google:
    anonymize_ip: ~
    tracking_id: ~
  provider: false
atom_feed:
  path: ~
author:
  avatar: ~
  bio: "Data Science Portfolio"
  email: asdasdasda@gamil.com
  links:
    -
      icon: "fas fa-fw fa-envelope-square"
      label: Email
    -
      icon: "fas fa-fw fa-link"
      label: Website
    -
      icon: mrityunjay-kumar-30ba51ba
      label: LinkedIn
    -
      icon: "fab fa-fw fa-twitter-square"
      label: Twitter
    -
      icon: "fab fa-fw fa-facebook-square"
      label: Facebook
    -
      icon: jaykumar1046
      label: GitHub
    -
      icon: "fab fa-fw fa-instagram"
      label: Instagram
  location: "Bangalore KA IN"
  name: "Mrityunjay Kumar Gupta"
baseurl: ~
bing_site_verification: ~
category_archive:
  path: /categories/
  type: liquid
comments:
  discourse:
    server: ~
  disqus:
    shortname: ~
  facebook:
    appid: ~
    colorscheme: ~
    num_posts: ~
  provider: ~
  utterances:
    issue_term: ~
    theme: ~
compress_html:
  clippings: all
  ignore:
    envs: development
description: "Data Science Portfolio."
encoding: utf-8
excerpt_separator: "\n\n"
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
facebook:
  app_id: ~
  publisher: ~
  username: ~
footer:
  links:
    -
      icon: "fab fa-fw fa-twitter-square"
      label: Twitter
    -
      icon: "fab fa-fw fa-facebook-square"
      label: Facebook
    -
      icon: "fab fa-fw fa-github"
      label: GitHub
    -
      icon: "fab fa-fw fa-gitlab"
      label: GitLab
    -
      icon: "fab fa-fw fa-bitbucket"
      label: Bitbucket
    -
      icon: "fab fa-fw fa-instagram"
      label: Instagram
google:
  instant_search: ~
  search_engine_id: ~
google_site_verification: ~
highlighter: rouge
include:
  - .htaccess
  - _pages
incremental: false
keep_files:
  - .git
  - .svn
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  toc_levels: "1..6"
locale: en-US
logo: ~
lsi: false
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
masthead_title: ~
minimal_mistakes_skin: default
name: "Mrityunjay Kumar Gupta"
naver_site_verification: ~
og_image: ~
paginate: 5
paginate_path: "/page:num/"
permalink: "/:categories/:title/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
reCaptcha:
  secret: ~
  siteKey: ~
repository: ~
sass:
  sass_dir: _sass
  style: compressed
search: ~
search_full_content: ~
search_provider: ~
social:
  links: ~
  name: ~
  type: ~
staticman:
  allowedFields: ~
  branch: ~
  commitMessage: ~
  endpoint: ~
  filename: ~
  format: ~
  generatedFields:
    date:
      options:
        format: ~
      type: ~
  moderation: ~
  path: ~
  requiredFields: ~
  transforms:
    email: ~
subtitle: ~
tag_archive:
  path: /tags/
  type: liquid
teaser: ~
timezone: ~
title: "Mrityunjay Kumar Gupta"
title_separator: "-"
twitter:
  username: ~
url: ~
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
words_per_minute: 200
yandex_site_verification: ~

theme: jekyll-theme-cayman